### ISSUE TITLE
Missing Source files

### ISSUE THREAD

**Issue by Nananas** [luboslenco/fox#1]
Hi,

Foxfw looks very interesting. I followed the wiki directions (more or less, other issues), but when eventually trying to run the project I get an error:
```
Generating Kha project.

../Sources/fox/trait/DaeScene.hx:5: characters 7-31 : Class not found : fox.sys.
importer.DaeData
```

But I cannot find this class in the Sources repo. (Animation and AnimationClip either) 
Is it not available (yet)?

**Comment by luboslenco** [comment]
Hello Nananas,

Thanks for your interest in this project! I had no idea someone would actually get this far already:)

The missing source files were Collada parsers but I just switched to OpenGex format, which is better suited for games. Hopefully it should compile fine now, but still a lot more work is needed to make this usable. Please let me know if you got it to run.

**Comment by Nananas** [comment]
Compiles now, no more missing-class errors.

**Comment by luboslenco** [comment]
Should be fixed now :)

(as mentioned here <https://github.com/luboslenco/fox_blender/issues/3>)

**Comment by Nananas** [comment]
Forgot to close :)
