### ISSUE TITLE
[HTML5, Chrome] Shader program link error

### ISSUE THREAD

**Issue by Nananas** [luboslenco/fox#2]
Building and running - for html5 - the start file (test.blend) in Google Chrome and IE gives the following error:
```
> Uncaught Could not link the shader program      |     kha.js:13887
```

But Firefox has no problem at all running the exact same thing...

This also happens with your [node-demo](https://ad2f2074b0cfcdbf734c117f07faf76f45a2a8a9.googledrive.com/host/0B22ElR_OUmfdWHBmRnJJajdKU1U/index.html) you posted on [twitter](https://twitter.com/luboslenco/status/557941198875545600)

I don't know if this is a fox only thing, but it is quite recent. Earlier demos - eg. chess - work just fine.

**Comment by luboslenco** [comment]
Ugh it also works in Safari but have the same error in Chrome. Thanks for report, I'm on it.

**Comment by luboslenco** [comment]
Should be fixed, had to change sampler name in shader. Both fox and [sources](https://github.com/luboslenco/sources) repo needs to be updated.

**Comment by Nananas** [comment]
Works :+1:
